apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-id1n
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-djik-tenant/rhtap-demo-app/hacbs-test-project-id1n@sha256:57cc6ab3fc5ac163d85984961fbeecfadddd298a96f1e4407890dd60a172c046
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
